[project]
name = "pokeapi-serri-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=0.3.2",
    "mcp-cli>=0.1.0",
    "mcp-use>=1.3.0",
    "mcp[cli]>=1.9.2",
]
